name: Build & Deploy

on:
  push:
    branches: [ wiki ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.99.0
        with:
          bundler-cache: true
          ruby-version: 3.1.0
      - run: JEKYLL_ENV=production bundle exec jekyll build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIAMONDFIREWIKI }}'
          channelId: live
          projectId: diamondfirewiki
